In [25]:
import pandas as pd

In [26]:
# The path to our CSV file
csv_path = "Resources/KickstarterData.csv"

# Read our Kickstarter data into pandas
kickstarter_df = pd.read_csv(csv_path)
kickstarter_df.head()

,id,photo,name,blurb,goal,pledged,state,slug,disable_communication,country,...,location,category,profile,spotlight,urls,source_url,friends,is_starred,is_backing,permissions
0,1645666704,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",The Class Act Players Theatre Company Presents...,The Class Act Players put on another one of th...,1500.0,2925.0,successful,the-class-act-players-theatre-company-presents...,False,US,...,"{""country"":""US"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
1,874638240,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,"A brand new play about love and entitlement, b...",2500.0,2936.0,successful,mr-incredible-by-camilla-whitehill-vault-festival,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
2,247074984,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",RUN,Yonni's pissed off in a world filled with scho...,1000.0,1200.0,successful,run-10,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
3,1941196813,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",9th International Meeting of Youth Theatre sap...,27. April bis 1. Mai 2016 in Brixen/Südtirol/I...,2000.0,2135.0,successful,9th-international-meeting-of-youth-theatre-sap...,False,IT,...,"{""country"":""IT"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN
4,421961595,"{""small"":""https://ksr-ugc.imgix.net/assets/012...",Get Conti to the Ed Fringe!,The Italia Conti 2nd years are going to Ed Fri...,1000.0,1250.0,successful,get-conti-to-the-ed-fringe,False,GB,...,"{""country"":""GB"",""urls"":{""web"":{""discover"":""htt...","{""urls"":{""web"":{""discover"":""http://www.kicksta...","{""background_image_opacity"":0.8,""should_show_f...",True,"{""web"":{""project"":""https://www.kickstarter.com...",https://www.kickstarter.com/discover/categorie...,NaN,NaN,NaN,NaN

In [27]:
# Get a list of all of our columns for easy reference
kickstarter_df.columns

Index(['id', 'photo', 'name', 'blurb', 'goal', 'pledged', 'state', 'slug',
       'disable_communication', 'country', 'currency', 'currency_symbol',
       'currency_trailing_code', 'deadline', 'state_changed_at', 'created_at',
       'launched_at', 'staff_pick', 'is_starrable', 'backers_count',
       'static_usd_rate', 'usd_pledged', 'creator', 'location', 'category',
       'profile', 'spotlight', 'urls', 'source_url', 'friends', 'is_starred',
       'is_backing', 'permissions'],
      dtype='object')

In [28]:
# Extract "name", "goal", "pledged", "state", "country", "staff_pick",
# "backers_count", and "spotlight"

kick_extract = kickstarter_df[["name", "goal", "pledged", "state", 
                              "country", "staff_pick", "backers_count", "spotlight"]]
kick_extract.head()

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.0,successful,US,False,17,True
1,MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,2500.0,2936.0,successful,GB,True,15,True
2,RUN,1000.0,1200.0,successful,GB,False,30,True
3,9th International Meeting of Youth Theatre sap...,2000.0,2135.0,successful,IT,False,24,True
4,Get Conti to the Ed Fringe!,1000.0,1250.0,successful,GB,False,28,True

In [29]:
# Remove projects that made no money at all
kick_extract = kick_extract.loc[kick_extract["pledged"] > 0]
kick_extract.head()

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.0,successful,US,False,17,True
1,MR INCREDIBLE by Camilla Whitehill - VAULT Fes...,2500.0,2936.0,successful,GB,True,15,True
2,RUN,1000.0,1200.0,successful,GB,False,30,True
3,9th International Meeting of Youth Theatre sap...,2000.0,2135.0,successful,IT,False,24,True
4,Get Conti to the Ed Fringe!,1000.0,1250.0,successful,GB,False,28,True

In [31]:
# Collect only those projects that were hosted in the US
kick_us = kick_extract.loc[kick_extract["country"] == "US"]
kick_us.head(50)

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight
0,The Class Act Players Theatre Company Presents...,1500.0,2925.0,successful,US,False,17,True
8,Forefront Festival 2015,7200.0,7230.0,successful,US,False,68,True
11,Hamlet the Hip-Hopera,9747.0,10103.0,successful,US,True,132,True
14,Pride Con,15000.0,15110.0,successful,US,False,60,True
15,En Garde Arts Emerging Artists Festival BOSSS,10000.0,10306.0,successful,US,True,80,True
17,"My Life in Michaels, a short play",1200.0,1265.0,successful,US,False,19,True
19,MSGA Junior Theater Festival 2016,1000.0,1300.0,successful,US,False,17,True
20,A Kingdom for a Stage! - Much Ado...,5000.0,6475.0,successful,US,False,105,True
31,Bartleby: a new musical at the MN Fringe,2000.0,2625.0,successful,US,False,25,True
32,"The Point, a show in the Women's Voices Theate...",3150.0,3150.0,successful,US,False,22,True
33,An Intimate Evening With Typhoid Mary,6700.0,7050.0,successful,US,False,102,True
39,"""Poor People"" at FringeNYC 2015",5500.0,5682.0,successful,US,True,34,True
42,Painting His Wings by Sinead Daly at FringeNYC,8000.0,8780.0,successful,US,False,140,True
43,"Lindsay Benner takes ""Book of Love"" to the Edi...",10939.0,13116.0,successful,US,False,160,True
44,Queen Mab's Steampunk and Fairie Street Festival,1300.0,3363.0,successful,US,True,62,True
45,RAFT: a new play by Emily Kitchens,7500.0,7826.0,successful,US,True,120,True
46,butyou'reaman in New York,5000.0,5717.0,successful,US,False,136,True
47,The Spinning Wheel: a son remixes a father's r...,20000.0,22602.0,successful,US,True,228,True
48,bring the children home...,2500.0,2500.0,successful,US,False,46,True
50,Bloomers Presents: LaughtHERfest,8000.0,9501.0,successful,US,True,102,True
52,#liberated,2000.0,2295.0,successful,US,False,62,True
54,Natasha Noman's Noman's Land | Aug 5-15th Edi...,7000.0,7571.0,successful,US,True,84,True
59,COSPLAY,5000.0,5000.0,successful,US,False,42,True
64,Love at the end of time--FringeNYC 2015,5000.0,5055.0,successful,US,False,22,True
67,The Devil You Say,2000.0,4000.0,successful,US,False,67,True
73,Les Midge: An Unexpected Musical of Hobbit Pro...,400.0,407.0,successful,US,False,15,True
74,"""Flying Ship"" Musical by Solo Youth Theater of...",3000.0,3030.0,successful,US,False,60,True
75,West Fulton Puppet Festival,5500.0,5637.0,successful,US,False,53,True
77,Take FLIGHT East to Edinburgh!,4772.0,5661.0,successful,US,False,103,True
79,Ex Communication,2500.0,2710.0,successful,US,False,61,True
80,Nomad Americana,900.0,1223.0,successful,US,False,28,True
82,The 5th Anniversary of the Working Theater Dir...,5000.0,5255.0,successful,US,False,55,True
84,Help The Kinsey Sicks Conquer the World's Larg...,24500.0,38779.0,successful,US,False,510,True
87,DEAD ZONE 805! Zombie Apocalypse Halloween Hau...,10000.0,10076.0,successful,US,False,52,True
88,BUILD THE GIANT SPACE BUG (& other fun stuff) ...,9000.0,9413.0,successful,US,False,105,True
94,English Premiere - Our Lady of the Clouds @ Ca...,1000.0,1060.0,successful,US,False,20,True
95,Fireball VII: Deadly Sins,1000.0,5334.0,successful,US,False,25,True
96,"The Trial Before Christmas (Troy, NY)",2000.0,2351.0,successful,US,False,63,True
97,MSGA -- Junior Theater Festival 2015,1200.0,1310.0,successful,US,False,15,True
98,Seekerfest STL,3500.0,3795.0,successful,US,False,39,True
99,The 90 Square Arts Festival - by 90X Arts,10000.0,10590.0,successful,US,False,35,True
100,OC@OC: Original Content at Off Center Season 1,25000.0,28730.0,successful,US,False,112,True
101,Black Hawk Children's Theatre Competes at AACT...,2200.0,2311.0,successful,US,False,27,True
102,She Came to Tea,1500.0,1640.0,successful,US,False,17,True
103,The Field at the Frigid Festival,3600.0,4291.0,successful,US,False,51,True
104,"BOOM! International Tour - Circus, Theatre, Ma...",14000.0,15169.0,successful,US,False,142,True
107,Peter/Wendy goes to the 2015 Edinburgh Fringe ...,10000.0,12003.0,successful,US,True,95,True
108,The Class Act Players,1100.0,1450.0,successful,US,False,17,True
110,Through the Glade,1200.0,1285.0,successful,US,False,16,True
111,PCSF's Semiannual 24-Hour Festival,1800.0,2017.0,successful,US,False,38,True

In [33]:
# Create a new column that finds the average amount pledged to a project
average_col = kick_us["pledged"] / kick_us["backers_count"]
kick_us["average pledge"] = average_col
print(kick_us.dtypes)
kick_us.head()

name               object
goal              float64
pledged           float64
state              object
country            object
staff_pick           bool
backers_count       int64
spotlight            bool
average pledge    float64
dtype: object

C:\Users\ericr\Anaconda3\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,name,goal,pledged,state,country,staff_pick,backers_count,spotlight,average pledge
0,The Class Act Players Theatre Company Presents...,1500.0,2925.0,successful,US,False,17,True,172.058824
8,Forefront Festival 2015,7200.0,7230.0,successful,US,False,68,True,106.323529
11,Hamlet the Hip-Hopera,9747.0,10103.0,successful,US,True,132,True,76.537879
14,Pride Con,15000.0,15110.0,successful,US,False,60,True,251.833333
15,En Garde Arts Emerging Artists Festival BOSSS,10000.0,10306.0,successful,US,True,80,True,128.825000

In [ ]:
# First convert "average_donation", "goal", and "pledged" columns to float

# Then Format to go to two decimal places, include a dollar sign, and use comma notation

In [ ]:
# Calculate the total number of backers for all US projects

In [ ]:
# Calculate the average number of backers for all US projects

In [ ]:
# Collect only those US campaigns that have been picked as a "Staff Pick"

In [ ]:
# Group by the state of the campaigns and see if staff picks matter (Seems to matter quite a bit)